# djaydev/autoconvert

FROM lsiobase/ubuntu:bionic
RUN apt update && \
apt install --no-install-recommends python3-pip python-setuptools libicu60 mediainfo libfreetype6 libc6 libutf8proc2 libtesseract4 libpng16-16 liblept5 pkgconf libva2 libva-drm2 expat libgomp1 -y && \
# cleanup
apt-get autoremove -y && \
apt-get clean && \
rm -rf \
  /tmp/* \
  /var/lib/apt/lists/*

RUN pip3 install watchdog 

# Copy ccextractor
COPY --from=djaydev/ccextractor:latest /usr/local/bin /usr/local/bin
# Copy ffmpeg
COPY --from=jellyfin/ffmpeg:latest /usr/local /usr/local/

# Copy the start script.
# COPY startapp.sh /etc/services.d/autoconvert/run
# Set the locale, to help Python and the user's applications deal with files that have non-ASCII characters
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

ENV UMAP ""
ENV GMAP ""

COPY sample.conf monitor.py runas.sh /files/
# Make sure it's readable by $UID
RUN chmod a+rwX /files

COPY 50_remap_ids.sh /etc/cont-init.d/50_remap_ids.sh
COPY 60_create_monitors.sh /etc/cont-init.d/60_create_monitors.sh
